apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-ui-role
rules:
  # k8s standard APIs
  - apiGroups:
      - ""
    resources:
      - events
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - argoproj.io
    resources:
      - eventsources
      - sensors
      - workflows
      - workfloweventbindings
      - workflowtemplates
      - clusterworkflowtemplates
      - cronworkflows
      - workflowtaskresults
    verbs:
      - create
      - delete
      - update
      - patch
      - get
      - list
      - watch
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-executor-role
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
