apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: llm
  name: llm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm
  strategy: {}
  template:
    metadata:
      labels:
        app: llm
    spec:
      containers:
      - image: ollama/ollama
        name: llm
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU
