apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend
      initContainers:
      - image: cv-platform-backend
        imagePullPolicy: IfNotPresent
        name: migration
        command: ["alembic", "upgrade", "head"]
        envFrom:
        - configMapRef:
           name: backend-cm
        - secretRef:
            name: backend-db
        resources: {}
      containers:
      - image: cv-platform-backend
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 3
        ports:
          - name: api
            containerPort: 8000
        name: api
        envFrom:
        - configMapRef:
           name: backend-cm
        - secretRef:
            name: backend-db
        resources: {}
