---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
  - name: web
    protocol: TCP
    port: 9090
    targetPort: web
  - name: api
    protocol: TCP
    port: 9000
    targetPort: api
